let state = {
  money: 10000,
  food: { hay: 30, meat: 20, produce: 15 },
  day: 1, month: 1, year: 1, ticketPrice: 20,
  ticketPriceImpact: 0,
  ticketSatisfactionImpact: 0,
  exhibits: {},
  builtEnclosures: {},
  zooFacilities: [],
  hiredStaff: [], // V0.7.0: Array of { uid, typeId, assignments[] }
  achievements: {},
  animalCounters: {},
  monthlyReports: [],
  moveState: { active: false, fromExhibit: null, animalIndex: null },
  uiMode: "normal",
  pendingAnimal: null,
  activeUpgradeExhibit: null,
  bredAnimals: 0,
  animalsSold: 0,
  daysSinceNewAnimal: 0,
  dailyVisitors: 0,
  visitorSpending: { food: 0, gifts: 0, total: 0 },
  visitorComplaints: [],
  amenities: {},
  visitorSatisfaction: 0,
  maintenance: { dailyMaintenanceCost: 0 },
  completedResearch: [],
  activeResearch: null,
  maintenanceWorkers: 0,
  maintenanceLevel: 0,
  tutorialStep: 0,
  tutorialSkipped: false,
  houses: {},
  recentDeathPenalty: 0,
  zooRating: 0,
  unnaturalDeaths: 0,
  naturalDeaths: 0,
  totalDeaths: 0,
  zooName: "My Zoo",
  monthlyIncomeTracker: 0
};

let data = {
  animals: [],
  upgrades: {},
  facilities: {},
  staff: [],
  amenities: {},
  achievements: [],
  researchProjects: {},
  exhibitTypes: {},
  houses: {}
};